import test from 'node:test';
import assert from 'node:assert/strict';
import {routePoints,pathData,pathBounds} from '../dist/connectors.js';

test('smart connectors route around an obstructing object',()=>{const start={x:0,y:50},end={x:300,y:50},obstacle={x:120,y:10,w:60,h:80},points=routePoints(start,end,'smart',[obstacle]);assert.ok(points.length>2);assert.deepEqual(points[0],start);assert.deepEqual(points.at(-1),end);assert.ok(points.some(p=>p.y<obstacle.y||p.y>obstacle.y+obstacle.h));});
test('connector modes produce line and curve paths with safe bounds',()=>{const points=[{x:-20,y:10},{x:80,y:60}];assert.match(pathData(points,'straight'),/ L /);assert.match(pathData(points,'curve'),/ C /);assert.deepEqual(pathBounds(points,10),{x:-30,y:0,w:120,h:70});});
test('smart avoid finds a clean route through multiple obstacles and rounds its turns',()=>{const start={x:0,y:40},end={x:400,y:40},obstacles=[{x:80,y:0,w:70,h:100},{x:210,y:-90,w:70,h:110},{x:320,y:0,w:45,h:100}],points=routePoints(start,end,'smart',obstacles);assert.deepEqual(points[0],start);assert.deepEqual(points.at(-1),end);assert.ok(points.length>3);assert.match(pathData(points,'smart'),/ Q /);});
test('smart curves honor user curve points while keeping automatic routing',()=>{const start={x:0,y:0},end={x:300,y:0},control={x:150,y:140},obstacle={x:115,y:45,w:70,h:55},points=routePoints(start,end,'smartCurve',[obstacle],[control]);assert.deepEqual(points[0],start);assert.deepEqual(points.at(-1),end);assert.ok(points.some(point=>point.x===control.x&&point.y===control.y));assert.match(pathData(points,'smartCurve'),/[CQ]/);});
test('manual curve points are emitted as smooth cubic segments',()=>{const points=routePoints({x:0,y:0},{x:200,y:0},'curve',[],[{x:60,y:90},{x:140,y:-40}]);const data=pathData(points,'curve');assert.equal((data.match(/ C /g)||[]).length,3);assert.match(data,/60 90/);assert.match(data,/140 -40/);});
